version: '3.8'

services:
  web:
    image: your_web_app_image  # Replace with your Docker image name
    container_name: ArRange-webapp
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

