version: "3.8"

services:
  web:
    build: .
    image: arrange:1.0   # Build and tag with version 1.0
    container_name: ArRange-webapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    networks:
      - arrange-net

  nginx:
    image: nginx:1.23
    container_name: nginx_proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - arrange-net

networks:
  arrange-net:
    driver: bridge
